version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ydavidovici35
      MYSQL_DATABASE: zeev-jewelry
      MYSQL_USER: yaakov
      MYSQL_PASSWORD: ydavidovici35

  backend:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    ports:
      - "9001:9000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3501:3000"
