version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: Zeev-Jewelry
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - db
    command: /bin/bash -c "composer install && npm install && npm run dev && php artisan key:generate && php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && apache2-foreground"

  db:
    image: mariadb:10.5
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  linter:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: linter
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    entrypoint: ["./vendor/bin/phpcs"]

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
