CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "roles" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null default 'web', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "username" varchar not null, "email" varchar not null, "password" varchar not null, "role" varchar not null default 'customer', "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_username_unique" on "users" ("username");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "categories" ("id" integer primary key autoincrement not null, "category_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "products" ("id" integer primary key autoincrement not null, "category_id" integer not null, "seller_id" integer not null, "product_name" varchar not null, "description" text not null, "price" numeric not null, "image_url" varchar not null, "created_at" datetime, "updated_at" datetime, "is_featured" tinyint(1) not null default '0', foreign key("category_id") references "categories"("id") on delete cascade, foreign key("seller_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "customers" ("id" integer primary key autoincrement not null, "user_id" integer not null, "address" varchar not null, "phone_number" varchar not null, "email" varchar not null, "is_guest" tinyint(1) not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE UNIQUE INDEX "customers_email_unique" on "customers" ("email");
CREATE TABLE IF NOT EXISTS "orders" ("id" integer primary key autoincrement not null, "customer_id" integer not null, "seller_id" integer not null, "order_date" datetime not null, "total_amount" numeric not null, "is_guest" tinyint(1) not null, "status" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("customer_id") references "customers"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "order_details" ("id" integer primary key autoincrement not null, "order_id" integer not null, "product_id" integer not null, "quantity" integer not null, "price" numeric not null, "created_at" datetime, "updated_at" datetime, foreign key("order_id") references "orders"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "payments" ("id" integer primary key autoincrement not null, "order_id" integer not null, "seller_id" integer not null, "payment_type" varchar not null, "payment_status" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("order_id") references "orders"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "shipping" ("id" integer primary key autoincrement not null, "order_id" integer not null, "seller_id" integer not null, "shipping_type" varchar not null, "shipping_cost" numeric not null, "shipping_status" varchar not null, "tracking_number" varchar not null, "shipping_address" varchar not null, "shipping_carrier" varchar not null, "recipient_name" varchar not null, "estimated_delivery_date" datetime not null, "additional_notes" text, "created_at" datetime, "updated_at" datetime, foreign key("order_id") references "orders"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "reviews" ("id" integer primary key autoincrement not null, "product_id" integer not null, "customer_id" integer not null, "review_text" text not null, "rating" integer not null, "review_date" datetime not null, "created_at" datetime, "updated_at" datetime, foreign key("product_id") references "products"("id") on delete cascade, foreign key("customer_id") references "customers"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "inventory" ("id" integer primary key autoincrement not null, "seller_id" integer not null, "product_id" integer not null, "location" varchar not null, "quantity" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("product_id") references "products"("id") on delete cascade, foreign key("seller_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "inventory_movements" ("id" integer primary key autoincrement not null, "inventory_id" integer not null, "movement_type" varchar not null, "quantity" integer not null, "movement_date" datetime not null, "created_at" datetime, "updated_at" datetime, foreign key("inventory_id") references "inventory"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "permissions" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "permissions_name_guard_name_unique" on "permissions" ("name", "guard_name");
CREATE TABLE IF NOT EXISTS "model_has_permissions" ("permission_id" integer not null, "model_type" varchar not null, "model_id" integer not null, foreign key("permission_id") references "permissions"("id") on delete cascade, primary key ("permission_id", "model_id", "model_type"));
CREATE INDEX "model_has_permissions_model_id_model_type_index" on "model_has_permissions" ("model_id", "model_type");
CREATE TABLE IF NOT EXISTS "model_has_roles" ("role_id" integer not null, "model_type" varchar not null, "model_id" integer not null, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("role_id", "model_id", "model_type"));
CREATE INDEX "model_has_roles_model_id_model_type_index" on "model_has_roles" ("model_id", "model_type");
CREATE TABLE IF NOT EXISTS "role_has_permissions" ("permission_id" integer not null, "role_id" integer not null, foreign key("permission_id") references "permissions"("id") on delete cascade, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("permission_id", "role_id"));
CREATE TABLE IF NOT EXISTS "settings" ("id" integer primary key autoincrement not null, "key" varchar not null, "value" text not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "settings_key_unique" on "settings" ("key");
CREATE TABLE IF NOT EXISTS "carts" ("id" integer primary key autoincrement not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "cart_items" ("id" integer primary key autoincrement not null, "cart_id" integer not null, "product_id" integer not null, "quantity" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("cart_id") references "carts"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime);
CREATE INDEX "password_reset_tokens_email_index" on "password_reset_tokens" ("email");
INSERT INTO migrations VALUES(1,'2024_05_30_000_create_roles_table',1);
INSERT INTO migrations VALUES(2,'2024_05_30_001_create_users_table',1);
INSERT INTO migrations VALUES(3,'2024_05_30_002_create_categories_table',1);
INSERT INTO migrations VALUES(4,'2024_05_30_003_create_products_table',1);
INSERT INTO migrations VALUES(5,'2024_05_30_004_create_customers_table',1);
INSERT INTO migrations VALUES(6,'2024_05_30_005_create_orders_table',1);
INSERT INTO migrations VALUES(7,'2024_05_30_006_create_order_details_table',1);
INSERT INTO migrations VALUES(8,'2024_05_30_007_create_payments_table',1);
INSERT INTO migrations VALUES(9,'2024_05_30_008_create_shipping_table',1);
INSERT INTO migrations VALUES(10,'2024_05_30_009_create_reviews_table',1);
INSERT INTO migrations VALUES(11,'2024_05_30_010_create_inventory_table',1);
INSERT INTO migrations VALUES(12,'2024_05_30_011_create_inventory_movements_table',1);
INSERT INTO migrations VALUES(13,'2024_06_09_215448_create_cache_table',1);
INSERT INTO migrations VALUES(14,'2024_06_28_103455_create_permission_tables',1);
INSERT INTO migrations VALUES(15,'2024_07_15_215443_create_settings_table',1);
INSERT INTO migrations VALUES(16,'2024_07_17_154123_create_carts_table',1);
INSERT INTO migrations VALUES(17,'2024_07_17_154227_create_cart_items_table',1);
INSERT INTO migrations VALUES(18,'2024_07_23_044654_add_is_featured_to_products_table',1);
INSERT INTO migrations VALUES(19,'2024_08_01_222803_create_password_reset_tokens_table',1);
