name: CI for Development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false  # Do not push the image to a registry
          tags: user/repo:latest  # Change 'user/repo' to your Docker Hub repository

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHP lint
        run: composer run-script lint

      - name: Run tests
        run: php artisan test