name: Run Tests

on: [push, pull_request]

jobs:
    backend-tests:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: your_database
                    MYSQL_USER: user
                    MYSQL_PASSWORD: password
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - uses: actions/checkout@v2

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0

            - name: Install Composer dependencies
              run: composer install

            - name: Copy .env.example to .env
              run: cp .env.example .env

            - name: Run migrations
              run: php artisan migrate --force

            - name: Run backend tests
              run: php artisan test

    frontend-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install dependencies
              run: npm install

            - name: Run frontend tests
              run: npm test
