name: Issue Management

on:
    issues:
        types: [opened, edited]

jobs:
    issue_triage:
        runs-on: ubuntu-latest

        steps:
            - name: Label new issues
              uses: actions-ecosystem/action-add-labels@v1
              with:
                  labels: 'triage'
